
set(APPLICATION_NAME "Soul-Mates" CACHE STRING "")

set(APPLICATION_VERSION_MAJOR 1)
set(APPLICATION_VERSION_MINOR 0)
set(APPLICATION_VERSION_PATCH 0)

string(JOIN "." APPLICATION_VERSION
    ${APPLICATION_VERSION_MAJOR}
    ${APPLICATION_VERSION_MINOR}
    ${APPLICATION_VERSION_PATCH}
)

set(APPLICATION_HOMEPAGE_URL "https://github.com/x7k3e21/Soul-Mates" CACHE STRING "")

set(EXECUTABLE_NAME "SoulMates" CACHE STRING "")